version: '3'
services:
  todofront:
    depends_on:
      - todoback
    build: ./todo-app/front-end
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=todoback
  todoback:
    build: ./todo-app/back-end
    ports:
      - "3001:3001"
  todotests:
    depends_on:
      - todofront
      - todoback
    build: ./todo-app/tests
    environment:
      - FRONT_HOST=todofront
